### ISSUE TITLE
DailyNote quarter and year 'automation' suggestions

### ISSUE THREAD

**Issue by xelaras** [ohlinn/vainilla-style#1]
Hi, 
instead of changing manually the start and end date of the quarter, I use startOf('quarter') and endOf('quarter')

In the DailyNote.md you can substitute this
```
🝮 <% moment(moment('21-09-30', 'YY-MM-DD')).diff(moment(tp.file.title, 'YY-MM-DD'), 'days') %> days left
```
with this:

```
🝮 <% moment(moment(tp.file.title, 'YY-MM-DD').endOf('quarter')).diff(moment(tp.file.title,'YY-MM-DD'),'days') %> days left
```

In a similar way, you can also use startOf('quarter') instead of '21-06-30'

Also, instead of putting manually the number of days in a year (365 or 366), you can calculate them with endOf('year') and startOf('year')

For example, I substituted this:
```
<progress value='<% moment(tp.file.title, 'YYYY-MM-DD').dayOfYear() %>' max='365'>
```
	
with:
```
<progress value="<% moment(tp.file.title,'YYYY-MM-DD').dayOfYear() %>" max="<%moment(moment(tp.file.title,'YYYY-MM-DD').endOf('year')).diff(moment(tp.file.title,'YYYY-MM-DD').startOf('year'),'days') %>">
```

Should this be not the right place to post this suggestion, please forgive me. I'm not used to github.
Thanks,
Alex

**Comment by ohlinn** [comment]
Thank you! I added that codes :)
